name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      - 
        run: clang-format --dry-run --Werror --verbose gly_type_render.h

  test-unit:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      - 
        run: make tests

  test-ocr:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        run: sudo apt-get -y install imagemagick tesseract-ocr --no-install-recommends
      - 
        run: make ocrtest
